"""initial schema

Revision ID: 10fc9f49a21e
Revises: 
Create Date: 2026-07-26 10:11:48.373536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fc9f49a21e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('whatsapp_user_id', sa.String(length=64), nullable=False),
    sa.Column('preferred_language', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_whatsapp_user_id'), ['whatsapp_user_id'], unique=True)

    op.create_table('inbound_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wa_message_id', sa.String(length=256), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_wa_message_id'), ['wa_message_id'], unique=True)

    op.create_table('procurement_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('raw_request', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('normalized_need', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.String(length=256), nullable=True),
    sa.Column('budget', sa.String(length=256), nullable=True),
    sa.Column('deadline', sa.String(length=256), nullable=True),
    sa.Column('company_context', sa.Text(), nullable=True),
    sa.Column('must_haves', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('last_clarifying_question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_cases_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_cases_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_cases_status'), ['status'], unique=False)

    op.create_table('rfqs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document_text', sa.Text(), nullable=False),
    sa.Column('fields_snapshot', sa.JSON(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('response_deadline', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['procurement_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfqs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfqs_status'), ['status'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['procurement_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_runs_case_id'), ['case_id'], unique=False)

    op.create_table('vendor_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_run_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['procurement_cases.id'], ),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_candidates_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_candidates_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_candidates_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_candidates_search_run_id'), ['search_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_candidates_search_run_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_candidates_position'))
        batch_op.drop_index(batch_op.f('ix_vendor_candidates_external_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_candidates_case_id'))

    op.drop_table('vendor_candidates')
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_runs_case_id'))

    op.drop_table('search_runs')
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfqs_status'))
        batch_op.drop_index(batch_op.f('ix_rfqs_case_id'))

    op.drop_table('rfqs')
    with op.batch_alter_table('procurement_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_cases_status'))
        batch_op.drop_index(batch_op.f('ix_procurement_cases_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_procurement_cases_category'))

    op.drop_table('procurement_cases')
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_messages_wa_message_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_status'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_sender'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_conversation_id'))

    op.drop_table('inbound_messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_whatsapp_user_id'))

    op.drop_table('conversations')
    # ### end Alembic commands ###
