"""add vendor, vendor_response, suppression

Revision ID: 45c4c8d1c255
Revises: 10fc9f49a21e
Create Date: 2026-07-26 11:05:26.576592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c4c8d1c255'
down_revision: Union[str, Sequence[str], None] = '10fc9f49a21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppressions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressions_key'), ['key'], unique=True)

    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('contact_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_source', sa.String(length=64), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vendors_phone'), ['phone'], unique=False)

    op.create_table('vendor_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('rfq_version', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('response_deadline', sa.String(length=256), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['procurement_cases.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_responses_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_responses_rfq_id'), ['rfq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_responses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_responses_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_responses_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_responses_status'))
        batch_op.drop_index(batch_op.f('ix_vendor_responses_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_responses_case_id'))

    op.drop_table('vendor_responses')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_phone'))
        batch_op.drop_index(batch_op.f('ix_vendors_external_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressions_key'))

    op.drop_table('suppressions')
    # ### end Alembic commands ###
