"""add quote extraction and approval states

Revision ID: 94652a5d8baf
Revises: f0df522bd287
Create Date: 2026-07-26 12:30:34.395709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94652a5d8baf'
down_revision: Union[str, Sequence[str], None] = 'f0df522bd287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_fields', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('extraction_status', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.drop_column('extraction_status')
        batch_op.drop_column('extracted_fields')

    # ### end Alembic commands ###
