"""add selected vendor and document text

Revision ID: c34d388f6e72
Revises: 94652a5d8baf
Create Date: 2026-07-26 12:33:42.553112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34d388f6e72'
down_revision: Union[str, Sequence[str], None] = '94652a5d8baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_vendor_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('document_text', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_procurement_cases_selected_vendor_id'), ['selected_vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_cases_selected_vendor_id'))
        batch_op.drop_column('document_text')
        batch_op.drop_column('selected_vendor_id')

    # ### end Alembic commands ###
