"""add vendor response reply fields

Revision ID: f0df522bd287
Revises: 45c4c8d1c255
Create Date: 2026-07-26 12:01:38.215108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0df522bd287'
down_revision: Union[str, Sequence[str], None] = '45c4c8d1c255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reply_message_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_responses', schema=None) as batch_op:
        batch_op.drop_column('reply_message_id')
        batch_op.drop_column('raw_reply')

    # ### end Alembic commands ###
